name: build web_client

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install wasm-pack
      uses: jetli/wasm-pack-action@v0.3.0
      with:
        version: 'latest'
    - name: Build web_client wasm binary
      working-directory: web_client
      run: wasm-pack build --release
#     - name: Run tests
#       working-directory: web_client
#       run: cargo test --verbose
    - name: Package web_client website
      working-directory: web_client
      run: npm ci && npm run build
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2
    - name: Upload web_client wasm binary to S3
      working-directory: web_client
      run: aws s3 cp dist/ s3://cloudbin.danielmcm.com/ --recursive --exclude "*" --include "*.wasm" --metadata-directive REPLACE --content-type "application/wasm"
    - name: Upload web_client website to S3
      working-directory: web_client
      run: aws s3 cp dist/ s3://cloudbin.danielmcm.com/ --recursive --exclude "*.wasm"
